name: Deploy Workflow

on:
  push:
    branches:
      - main  # Cuando se haga push en master

jobs:
  deploy:
    runs-on: self-hosted  # Usa el runner en EC2
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Reiniciar servidor con PM2
        run: |
          npm install
          npm install express
          npm install dotenv
          sudo pm2 reload PresArt
        env:
          DDNS_HOST: ${{ secrets.DDNS_HOST }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DATABASE: ${{ secrets.DB_DATABASE }}
          PORT: ${{ secrets.PORT }}